spring:
  application:
    name: kip-gateway

  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
      config:
        server-addr: nacos-server:8848
    sentinel:
      transport:
        dashboard: sentinel-dashboard:8080

server:
  port: 8888

logging:
  level:
    root: WARN
    org.springframework.cloud.gateway: INFO
    xyz.kip: INFO
