apiVersion: v1
kind: ConfigMap
metadata:
  name: kip-gateway-config
  namespace: kip-poc
  labels:
    app: kip-gateway
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "9527"
  NACOS_SERVER_ADDR: "10.42.0.125:8848"
  NACOS_NAMESPACE: "74a3fe73-35c1-474e-ade8-9bc460b3f398"
  NACOS_GROUP: "K8S_POC"
  NACOS_CONFIG_ENABLED: "true"
  NACOS_DISCOVERY_ENABLED: "false"
  NACOS_REGISTER_ENABLED: "false"
  NACOS_AUTO_REGISTRATION_ENABLED: "false"
  KIP_APP_BASE_URL: "http://kip-app:8010"
  KIP_AUTH_BASE_URL: "http://kip-auth:5001"
  REDIS_HOST: "kip-redis"
  REDIS_PORT: "6379"
