apiVersion: v1
kind: ConfigMap
metadata:
  name: kip-gateway-config
  namespace: kip-poc
  labels:
    app: kip-gateway
data:
  SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
  SERVER_PORT: "${SERVER_PORT}"
  NACOS_SERVER_ADDR: "${NACOS_SERVER_ADDR}"
  NACOS_NAMESPACE: "${NACOS_NAMESPACE}"
  NACOS_GROUP: "${NACOS_GROUP}"
  NACOS_CONFIG_ENABLED: "${NACOS_CONFIG_ENABLED}"
  NACOS_DISCOVERY_ENABLED: "${NACOS_DISCOVERY_ENABLED}"
  NACOS_REGISTER_ENABLED: "${NACOS_REGISTER_ENABLED}"
  NACOS_AUTO_REGISTRATION_ENABLED: "${NACOS_AUTO_REGISTRATION_ENABLED}"
  KIP_APP_BASE_URL: "${KIP_APP_BASE_URL}"
  KIP_AUTH_BASE_URL: "${KIP_AUTH_BASE_URL}"
  REDIS_HOST: "${REDIS_HOST}"
  REDIS_PORT: "${REDIS_PORT}"
