apiVersion: v1
kind: Secret
metadata:
  name: kip-gateway-secret
  labels:
    app: kip-gateway
type: Opaque
stringData:
  REDIS_PASSWORD: "AFDC2B7F13A3"
  AUTH_JWT_SECRET: "KipAuthServiceSecretKeyMustBeAtLeast32CharactersLongForHS256"
