apiVersion: v1
kind: Service
metadata:
  name: kip-gateway
  labels:
    app: kip-gateway
spec:
  type: NodePort
  selector:
    app: kip-gateway
  ports:
    - name: http
      port: 9527
      targetPort: http
      nodePort: 30527
