apiVersion: v1
kind: Service
metadata:
  name: kip-gateway
  labels:
    app: kip-gateway
spec:
  type: ClusterIP
  selector:
    app: kip-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8888

