spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: kip-gateway
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true

  cloud:
    service-registry:
      auto-registration:
        enabled: ${NACOS_AUTO_REGISTRATION_ENABLED:false}
    nacos:
      config:
        enabled: ${NACOS_CONFIG_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:10.42.0.125:8848}
        file-extension: yml
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        namespace: ${NACOS_NAMESPACE:}
        refresh-enabled: true
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:false}
        server-addr: ${NACOS_SERVER_ADDR:10.42.0.125:8848}
        register-enabled: ${NACOS_REGISTER_ENABLED:false}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        namespace: ${NACOS_NAMESPACE:}

    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

  jackson:
    default-property-inclusion: non_empty
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,prometheus,refresh
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    gateway:
      access: unrestricted
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
